<template>
  <b-modal id="orderTimeline" ref="orderTimeline" title="Send Connect Request to Buyer" @hide="onModalClose" hide-footer hide-header>
    <div class="card bg-gradient-default shadow">
      <div class="card-header bg-transparent">
        <h3 class="mb-0 text-white">Order Timeline</h3>
      </div>
      <div class="card-body">
        <div class="timeline timeline-one-side" data-timeline-content="axis" data-timeline-axis-style="dashed">
          <div class="timeline-block">
            <span class="timeline-step badge-success">
              <i class="ni ni-cart"></i>
            </span>
            <div class="timeline-content">
              <small class="text-light font-weight-bold">{{dateTime(details.created_at)}}</small>
              <h5 class="text-white mt-3 mb-0">Order Created</h5>
            </div>
          </div>
          <div class="timeline-block">
            <span class="timeline-step badge-danger">
              <i class="ni ni-delivery-fast"></i>
            </span>
            <div class="timeline-content">
              <small class="text-light font-weight-bold">{{dateTime(details.details.PAT)}}</small>
              <h5 class="text-white mt-3 mb-0">Assigned / Accepted by Driver</h5>
            </div>
          </div>
          <div class="timeline-block">
            <span class="timeline-step badge-info">
              <i class="fas fa-file-invoice"></i>
            </span>
            <div class="timeline-content">
              <small class="text-light font-weight-bold">{{dateTime(details.details.PAT)}}</small>
              <h5 class="text-white mt-3 mb-0">Invoice Generated by Driver</h5>
            </div>
          </div>
          <div class="timeline-block">
            <span class="timeline-step badge-success">
              <i class="ni ni-like-2"></i>
            </span>
            <div class="timeline-content">
              <small class="text-light font-weight-bold">{{dateTime(details.details.PAT)}}</small>
              <h5 class="text-white mt-3 mb-0">Invoice Accepted by Customer</h5>
            </div>
          </div>
          <div class="timeline-block">
            <span class="timeline-step badge-danger">
              <i class="ni ni-building"></i>
            </span>
            <div class="timeline-content">
              <small class="text-light font-weight-bold">10:30 AM</small>
              <h5 class="text-white mt-3 mb-0">Dropped at Laundry</h5>
            </div>
          </div>
          <div class="timeline-block">
            <span class="timeline-step badge-info">
              <i class="ni ni-delivery-fast"></i>
            </span>
            <div class="timeline-content">
              <small class="text-light font-weight-bold">10:30 AM</small>
              <h5 class="text-white mt-3 mb-0">Assigned for Delivery</h5>
            </div>
          </div>
          <div class="timeline-block">
            <span class="timeline-step badge-danger">
              <i class="ni ni-check-bold"></i>
            </span>
            <div class="timeline-content">
              <small class="text-light font-weight-bold">10:30 AM</small>
              <h5 class="text-white mt-3 mb-0">Delivered to Customer</h5>
            </div>
          </div>
        </div>
      </div>
    </div>
  </b-modal>
</template>


<script>
  export default{
    data(){
      return{
        message: null,
        errors:{},
      }
    },
    methods:{
      hideModal() {
        this.$refs['orderTimeline'].hide()
      },
      onModalClose(){

      },
      dateTime(date){
        var date = new Date(date+' UTC')
        return this.$moment(date).format("ddd MMM DD YYYY [at] HH:mm A");
      },
    },
    computed: {
      details(){
        return this.$parent.details
      }
    },
  }

</script>

<style type="text/css" scoped>
  .modal-body {
    padding: 0 !important;
  }
  body{
    display: none;
  }
</style>